const express = require('express')
const monito_BeiKe = require('../controller/monito/monito_BeiKe')
const monito_JD = require('../controller/monito/monito_JD')
const monito_WeiBo = require('../controller/monito/monito_WeiBo')
const check = require('../middlewares/check')
const router = express.Router()
router.get('/house/addhouse', check.checkAdmin, monito_BeiKe.addhouse)
router.delete('/house/delhouse', check.checkAdmin, monito_BeiKe.delhouse)
router.get('/house/gethouse', check.checkAdmin, monito_BeiKe.gethouse)
router.get('/jd/addgoods', check.checkAdmin, monito_JD.addgoods)
router.delete('/jd/delgoods', check.checkAdmin, monito_JD.delgoods)
router.get('/jd/getgoods', check.checkAdmin, monito_JD.getgoods)
router.get('/wb/getWatchList', check.checkAdmin, monito_WeiBo.getwatchList)
router.get('/wb/addWatchList', check.checkAdmin, monito_WeiBo.addWatchList)
router.delete('/wb/delWatchList', check.checkAdmin, monito_WeiBo.delWatchList)
module.exports = router